### ISSUE TITLE
panic on starting transient unit

### ISSUE THREAD

**Issue by mrunalp** [coreos/go-systemd#146]
I am working on enabling systemd-cgroup support in runc by adding a flag and seeing this error.
Here is the branch
https://github.com/opencontainers/runc/compare/master...mrunalp:systemd_cgroups?expand=1
```
[root@dhcp-16-129 testroot]# runc --systemd-cgroup start 1234
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x68839f]

goroutine 1 [running]:
panic(0x7a5460, 0xc820012130)
        /usr/lib/golang/src/runtime/panic.go:464 +0x3e6
github.com/coreos/go-systemd/dbus.(*Conn).startJob(0x0, 0x0, 0x8a26e0, 0x33, 0xc820136100, 0x4, 0x4, 0x0, 0x0, 0x0)
        /root/gosrc/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods.go:47 +0x32f
github.com/coreos/go-systemd/dbus.(*Conn).StartTransientUnit(0x0, 0xc820122210, 0xf, 0x81f300, 0x7, 0xc820148000, 0x7, 0x8, 0x0, 0xc820122245, ...)
        /root/gosrc/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods.go:137 +0x2d5
github.com/opencontainers/runc/libcontainer/cgroups/systemd.(*Manager).Apply(0xc82000fac0, 0x27a3, 0x0, 0x0)
        /root/gosrc/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go:229 +0x1086
github.com/opencontainers/runc/libcontainer.(*initProcess).start(0xc820132000, 0x0, 0x0)
        /root/gosrc/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/process_linux.go:247 +0x41e
github.com/opencontainers/runc/libcontainer.(*linuxContainer).Start(0xc8200ce180, 0xc8200e6d80, 0x0, 0x0)
        /root/gosrc/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/container_linux.go:189 +0x1d2
main.(*runner).run(0xc8200d6f90, 0xc820090930, 0x8, 0x0, 0x0)
        /root/gosrc/src/github.com/opencontainers/runc/utils.go:342 +0x630
main.startContainer(0xc82008ec60, 0xc820090900, 0x0, 0x0, 0x0)
        /root/gosrc/src/github.com/opencontainers/runc/start.go:122 +0x406
main.glob.func11(0xc82008ec60)
        /root/gosrc/src/github.com/opencontainers/runc/start.go:72 +0x17b
github.com/codegangsta/cli.Command.Run(0x81f838, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8703a0, 0x1a, 0x8d16a0, ...)
        /root/gosrc/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:137 +0x1081
github.com/codegangsta/cli.(*App).Run(0xc82008ea20, 0xc82000a200, 0x4, 0x4, 0x0, 0x0)
        /root/gosrc/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:176 +0xffa
main.main()
        /root/gosrc/src/github.com/opencontainers/runc/main.go:123 +0xc8e
```

**Comment by philips** [comment]
@mrunalp can you post the bundle you are using somewhere?

**Comment by mrunalp** [comment]
@philips I am using https://github.com/jpetazzo/docker-busybox/raw/buildroot-2014.11/rootfs.tar
as the rootfs and the default spec generated by running `runc spec`

**Comment by lucab** [comment]
```
github.com/coreos/go-systemd/dbus.(*Conn).StartTransientUnit(0x0, 0xc820122210, 0xf, 0x81f300, 0x7, 0xc820148000, 0x7, 0x8, 0x0, 0xc820122245, ...)
        /root/gosrc/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods.go:137 +0x2d5
```

Looking at the first argument there, It looks like this is being called on a `nil` receiver.

**Comment by lucab** [comment]
@mrunalp would you please have another look at your code and check if `*Conn` is `nil` on your side at the time of the panic? I think this panic may be due to a problem in the caller...

**Comment by mrunalp** [comment]
Yeah we did fix this long time back. We can close this issue. Thanks!

**Comment by lucab** [comment]
Thanks for following up, closing.
