### ISSUE TITLE
JournalReader.Read() doesn't return the correct number of bytes that's been read

### ISSUE THREAD

**Issue by yifan-gu** [coreos/go-systemd#172]
Here in [JournalReader.Read()](https://github.com/coreos/go-systemd/blob/master/sdjournal/read.go#L132), the returned length can be larger than what's actually been read when the buffer provided is not big enough.
Which will cause a panic in https://golang.org/src/bytes/buffer.go#L177. (go 1.6.2 linux/amd64)

I found this when doing `kubectl logs on some pods`.

Here is the panic trace from the rkt api service:
```
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: panic: runtime error: slice bounds out of range [recovered]
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]:         panic: runtime error: slice bounds out of range
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: goroutine 6580 [running]:
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: panic(0xdbd0c0, 0xc82000c030)
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]:         /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: io/ioutil.readAll.func1(0xc8201b9950)
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]:         /usr/lib/go-1.6/src/io/ioutil/ioutil.go:30 +0x11e
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: panic(0xdbd0c0, 0xc82000c030)
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]:         /usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: bytes.(*Buffer).ReadFrom(0xc8201b98a8, 0x7f9d80c0b780, 0xc82012c428, 0x0, 0x0, 0x0)
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]:         /usr/lib/go-1.6/src/bytes/buffer.go:177 +0x322
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: io/ioutil.readAll(0x7f9d80c0b780, 0xc82012c428, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]:         /usr/lib/go-1.6/src/io/ioutil/ioutil.go:33 +0x156
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: io/ioutil.ReadAll(0x7f9d80c0b780, 0xc82012c428, 0x0, 0x0, 0x0, 0x0, 0x0)
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]:         /usr/lib/go-1.6/src/io/ioutil/ioutil.go:42 +0x51
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: main.(*v1AlphaAPIServer).GetLogs(0xc82012c418, 0xc8200485c0, 0x7f9d80c0b730, 0xc8203de760, 0x0, 0x0)
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]:         /opt/build-rkt/gopath/src/github.com/coreos/rkt/rkt/api_service.go:767 +0x734
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: github.com/coreos/rkt/api/v1alpha._PublicAPI_GetLogs_Handler(0xe69940, 0xc82012c418, 0x7f9d80c0b698, 0xc82013c960, 0x0, 0x0)
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]:         /opt/build-rkt/gopath/src/github.com/coreos/rkt/api/v1alpha/api.pb.go:1088 +0x175
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: google.golang.org/grpc.(*Server).processStreamingRPC(0xc8202d9740, 0x7f9d80bf6158, 0xc82019abd0, 0xc820372540, 0xc820312040, 0x1580720, 0xc820199230, 0x0, 0x0)
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]:         /opt/build-rkt/gopath/src/github.com/coreos/rkt/Godeps/_workspace/src/google.golang.org/grpc/server.go:421 +0x2dc
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: google.golang.org/grpc.(*Server).handleStream(0xc8202d9740, 0x7f9d80bf6158, 0xc82019abd0, 0xc820372540, 0xc820199230)
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]:         /opt/build-rkt/gopath/src/github.com/coreos/rkt/Godeps/_workspace/src/google.golang.org/grpc/server.go:493 +0x114e
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: google.golang.org/grpc.(*Server).Serve.func2.1.1(0xc8202d9740, 0x7f9d80bf6158, 0xc82019abd0, 0xc820372540, 0xc820199230, 0xc8202d2420)
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]:         /opt/build-rkt/gopath/src/github.com/coreos/rkt/Godeps/_workspace/src/google.golang.org/grpc/server.go:278 +0x49
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]: created by google.golang.org/grpc.(*Server).Serve.func2.1
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i rkt[1212]:         /opt/build-rkt/gopath/src/github.com/coreos/rkt/Godeps/_workspace/src/google.golang.org/grpc/server.go:280 +0x5ac
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i systemd[1]: rkt-api-service.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i systemd[1]: rkt-api-service.service: Unit entered failed state.
Jun 11 01:05:48 yifan-test-rkt-minion-group-fc7i systemd[1]: rkt-api-service.service: Failed with result 'exit-code'.
```

cc @jonboulle @iaguis @alban @euank

**Comment by yifan-gu** [comment]
Actually I am not sure on top of my head how we are going to handle this when the given slice is not big enough to copy all the bytes...
