### ISSUE TITLE
Fail sdjournal on armhf architecture 

### ISSUE THREAD

**Issue by AndreyMaslow** [coreos/go-systemd#427]
I have a program, that analyze journalctl logs on the  embedded device. It works fine on arm64, but when i rebuild it for armhf (debian 10), i get the error 

```
goroutine 106 [syscall]:
runtime.cgocall(0xa82dac, 0x1a5f840)
        /usr/local/go/src/runtime/cgocall.go:158 +0x5c fp=0x1a5f828 sp=0x1a5f810 pc=0x138b0
github.com/coreos/go-systemd/v22/internal/dlopen._Cfunc_dlopen(0x92900698, 0x1)
        _cgo_gotypes.go:108 +0x34 fp=0x1a5f83c sp=0x1a5f828 pc=0x377d20
github.com/coreos/go-systemd/v22/internal/dlopen.GetHandle({0x1468c98, 0x4, 0x4})
        /go/pkg/mod/github.com/coreos/go-systemd/v22@v22.5.0/internal/dlopen/dlopen.go:45 +0xb0 fp=0x1a5f860 sp=0x1a5f83c pc=0x377fa0
github.com/coreos/go-systemd/v22/sdjournal.getFunction({0xc7ab9f, 0xf})
        /go/pkg/mod/github.com/coreos/go-systemd/v22@v22.5.0/sdjournal/functions.go:46 +0xb4 fp=0x1a5f890 sp=0x1a5f860 pc=0x378638
github.com/coreos/go-systemd/v22/sdjournal.NewJournal()
        /go/pkg/mod/github.com/coreos/go-systemd/v22@v22.5.0/sdjournal/journal.go:427 +0x40 fp=0x1a5f8b8 sp=0x1a5f890 pc=0x37b12c
github.com/coreos/go-systemd/v22/sdjournal.NewJournalReader({0x0, 0x64, {0x0, 0x0}, {0x18a3370, 0x1, 0x1}, {0x0, 0x0}, 0xce71c8})
        /go/pkg/mod/github.com/coreos/go-systemd/v22@v22.5.0/sdjournal/read.go:82 +0xc0 fp=0x1a5f960 sp=0x1a5f8b8 pc=0x378914
github.com/FaceChainTeam/panelgo/src/device.NewSerive.func1({0x0, 0x64, {0x0, 0x0}, {0x18a3370, 0x1, 0x1}, {0x0, 0x0}, 0xce71c8})
        /panelgo/src/device/device.go:80 +0x20 fp=0x1a5f9a0 sp=0x1a5f960 pc=0x3a4310
github.com/FaceChainTeam/panelgo/src/device/logstorage.(*Service).ReadJournaldUnitLog(0x180f330, {0xc7ad70, 0xf}, 0x64)
        /panelgo/src/device/logstorage/logstorage.go:68 +0xf8 fp=0x1a5fa30 sp=0x1a5f9a0 pc=0x380ec0
github.com/FaceChainTeam/panelgo/src/apiserver.(*server).readJournaldUnitLogHandler(0x1b31d00, 0x1badbd0, {0xc7ad70, 0xf})
        /panelgo/src/apiserver/handler_log.go:250 +0x12c fp=0x1a5fa78 sp=0x1a5fa30 pc=0xa6093c
github.com/FaceChainTeam/panelgo/src/apiserver.(*server).handlerLogUpdater(0x1b31d00, 0x1badbd0)
        /panelgo/src/apiserver/handler_log.go:131 +0xd8 fp=0x1a5faa8 sp=0x1a5fa78 pc=0xa607f0
github.com/FaceChainTeam/panelgo/src/apiserver.(*server).handlerLogUpdater-fm(0x1badbd0)
        <autogenerated>:1 +0x30 fp=0x1a5fab4 sp=0x1a5faa8 pc=0xa6b8b0
```

**Comment by kolyshkin** [comment]
I am sorry that no one ever get to you earlier on this. This must be a build problem of some sort; the only fix to this area is #431 and it does not seem related from the first glance.

In any case, this is kinda old and we haven't seen anything like it (meaning there are no similar bug reports) so I'm inclined to close it. If you still see the issue, please open a new bug.
